---
- name: install php and php-mysql
  yum:
    state: present
    name:
      - php
      - php-mysql
  notify: restart httpd

- name: copy phpinfo page for testing
  copy: src=info.php dest=/var/www/html/info.php